#include <iostream>

using namespace std;

int divisao_de_dez_por( int divisor )
{
   // prevendo entrada inválida
   if( divisor == 0 )
   {
      throw "divisão por zero";
   }

   return 10 / divisor;
}

int main()
{
   int div, resultado;

   cin >> div; // obtém do usuário um número inteiro

   try
   {
      resultado = divisao_de_dez_por( div );
   }
   catch( const char *e )
   { // código será redirecionado para cá caso ( div == 0 )
      resultado = 0; // recuperação do sistema
      cout << "Houve uma exceção: " << e << endl;
   }
}
